// let arr = [].map.call(document.querySelectorAll('td'), (node) => {
//     return node.innerText;
// })

module.exports.descriptor = [
    "Peaceful",
    "Picturesque",
    "Unspoiled",
    "Vibrant",
    "Lively",
    "Inspiring",
    "Homey",
    "Fresh",
    "Fascinating",
    "Enchanting",
    "Cosmopolitan",
    "Charming",
    "Calm",
    "Bustling",
    "Beautiful",
    "Alive",
    "Nightmarish",
    "Polluted",
    "Stormy",
    "Touristy",
    "Ugly",
    "Ancient",
    "Contemporary",
    "Majestic",
    "Magical",
    "Quiet",
    "Traditional",
    "Mystical",
    "Bleak", ,
    "Boring",
    "Crowded",
    "Desolate",
    "Dull",
    "Expensive",
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond'];

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow'
]

